%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jpat943/Documents/2024/TIDES/Kneading Diagram/Find Maxima/results_maxima.dat
%
% Auto-generated by MATLAB on 02-Sep-2024 14:20:47

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "Var4", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
results_maxima = readtable("/Users/jpat943/Documents/2024/TIDES/Kneading Diagram/Find Maxima/results_maxima.dat", opts);

%% Convert to output type
results_maxima = table2array(results_maxima);

%% Clear temporary variables
clear opts